# Generated by Django 5.1.6 on 2025-02-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tag_order_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop')], max_length=200, null=True),
        ),
    ]
